name: ğŸ«´ Pull Request

on:
  pull_request:
    branches: 
      - main
        
env:
  sln-path: exercise/c#/AdventOfCraft.sln

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: ğŸ— Build and Test
    
    steps:

      - name: ğŸ“© Checkout Code
        uses: actions/checkout@v4

      - name: ğŸ”— Install dependencies
        run: dotnet restore ${{ env.sln-path }}

      - name: ğŸ— Build solution
        run: dotnet build ${{ env.sln-path }} --configuration Release --no-restore

      - name: âœ… Test solution
        run: dotnet test ${{ env.sln-path }} --configuration Release --no-restore --no-build